spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: desafioDeCadastroAPI
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PW}
server:
  servlet:
    context-path: /desafio-cadastro